### PR TITLE
Generic dictionary for input handling, because Godot dictionaries bug out.

### PR DESCRIPTION
**Pull request by FireBrandMint**
It took so long for me to figure out how to do this, it looked impossible but i found a way.

And yes: the syncDebugger bugs out, but because the rest somehow doesn't i consider it a sucess. ("somehow" because i went through this serialization code for inputs blindly, that was so exausting that i tought it wouldn't work, i tought i did everything wrong before testing)

Also there's "add files via upload" because the godot plugin for github bugged out of it's mind so i had to copypaste the code manually.

### CODE REVIEW

**Comment by lmichaudel** [comment]
Thanks for this PR, I will look into it asap, nice work dude.
Also don't worry about the sync debugger not working, it take Godot dictionaries arguments, so using c# ones or custom solution break it for sure 🙂

**Comment by FireBrandMint** [comment]
Thanks, by the way, what will we do for floating point difference for different machines causing desync? Is there something already handling it on the code? I will open the issue with more things i have to say, if it's already solved please close it.

**Comment by lmichaudel** [comment]
The thing is that this repo only handle the "logic" you give him your inputs, and it will notify you when you need to load a state / simulate a frame. A bit like GGPO is doing.
This mean it's the user work to handle floats themselves, in their own system.
A demo is included, yet it is not deterministic

**Comment by FireBrandMint** [comment]
That's why in the issues tab i suggested sending the entire world state once every X seconds, that doesn't make it more deterministic but it corrects any desync. Hoever that's hard, that's really hard (i even tried to make my own SDK using a system based on periodically resimulating with a counterfeit GGPO, for the gameplay, it didn't work because i couldn't figure out how GGPO worked)

**Review by lmichaudel — APPROVED** [review]

**Pull request merged**
